/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description Static vocabulary, read straight off app/services/activities.py - no
         *     database access, so nothing here can drift from what POST /completions
         *     and the CHECK constraints actually enforce.
         */
        get: operations["list_activities_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Completions */
        get: operations["list_completions_completions_get"];
        put?: never;
        /** Create Completion */
        post: operations["create_completion_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/completions/{completion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Completion */
        delete: operations["delete_completion_completions__completion_id__delete"];
        options?: never;
        head?: never;
        /** Update Completion */
        patch: operations["update_completion_completions__completion_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Update Plan */
        patch: operations["update_plan_plans__plan_id__patch"];
        trace?: never;
    };
    "/plans/{plan_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_plans__plan_id__schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/schedule-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_plans__plan_id__schedule_entries_get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_plans__plan_id__schedule_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/schedule-entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_plans__plan_id__schedule_entries__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Entry */
        patch: operations["update_entry_plans__plan_id__schedule_entries__entry_id__patch"];
        trace?: never;
    };
    "/plans/{plan_id}/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workouts */
        get: operations["list_workouts_plans__plan_id__workouts_get"];
        put?: never;
        /** Create Workout */
        post: operations["create_workout_plans__plan_id__workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Workout */
        delete: operations["delete_workout_plans__plan_id__workouts__workout_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout */
        patch: operations["update_workout_plans__plan_id__workouts__workout_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivitiesResponse */
        ActivitiesResponse: {
            /** Activities */
            activities: components["schemas"]["ActivityInfo"][];
            /** Units */
            units: components["schemas"]["UnitInfo"][];
        };
        /**
         * Activity
         * @enum {string}
         */
        Activity: "running" | "walking" | "cycling" | "swimming" | "strength_training" | "cardio" | "stretching_mobility" | "other";
        /** ActivityInfo */
        ActivityInfo: {
            activity: components["schemas"]["Activity"];
            default_unit: components["schemas"]["Unit"] | null;
            /** Display Name */
            display_name: string;
            /** Units */
            units: components["schemas"]["Unit"][];
        };
        /** CompletionCreate */
        CompletionCreate: {
            activity?: components["schemas"]["Activity"] | null;
            /** Note */
            note?: string | null;
            /**
             * On Date
             * Format: date
             */
            on_date: string;
            /** Schedule Entry Id */
            schedule_entry_id?: string | null;
            unit?: components["schemas"]["Unit"] | null;
            /** Value */
            value?: number | string | null;
        };
        /** CompletionRead */
        CompletionRead: {
            activity: components["schemas"]["Activity"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Note */
            note: string | null;
            /**
             * On Date
             * Format: date
             */
            on_date: string;
            /** Schedule Entry Id */
            schedule_entry_id: string | null;
            source: components["schemas"]["CompletionSource"];
            unit: components["schemas"]["Unit"] | null;
            /** Value */
            value: number | null;
        };
        /**
         * CompletionSource
         * @description Written once at creation, never derived or updated - schedule_entry_id
         *     gets nulled out (by ON DELETE SET NULL) the moment its entry or workout is
         *     deleted, so it cannot answer "was this scheduled?" after the fact. Plan
         *     adherence must not change retroactively just because someone tidied up
         *     their plan.
         * @enum {string}
         */
        CompletionSource: "scheduled" | "standalone";
        /** CompletionUpdate */
        CompletionUpdate: {
            /** Note */
            note?: string | null;
            unit?: components["schemas"]["Unit"] | null;
            /** Value */
            value?: number | string | null;
        };
        /**
         * DayScheduleRead
         * @description No `date` field - the date is already the key this value sits under in
         *     ScheduleResponse.days, so it isn't duplicated here.
         */
        DayScheduleRead: {
            /** Cancelled */
            cancelled: components["schemas"]["EntryRefRead"][];
            /** Completed */
            completed: boolean;
            /** Entries */
            entries: components["schemas"]["ResolvedEntryRead"][];
            status: components["schemas"]["DayStatus"];
        };
        /**
         * DayStatus
         * @description Day-level status is a presentation convenience for compact rendering
         *     (e.g. a single calendar-cell badge) - `entries` and `cancelled` are the
         *     authoritative data. Clients must not branch on this status alone in a
         *     detailed view: a SCHEDULED day can still carry unrelated cancelled
         *     entries (see resolve()'s mixed-day precedence), and SUBSTITUTED only
         *     means *at least one* surviving entry that day is a substitution.
         *
         *     These string values are part of the public wire contract - app/schemas/
         *     imports this enum directly for the API response, so renaming a member
         *     here changes the API, not just an internal detail.
         * @enum {string}
         */
        DayStatus: "empty" | "scheduled" | "cancelled" | "substituted";
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "time" | "distance" | "count";
        /**
         * EntryRefRead
         * @description Minimal reference to another entry - used both for what a substitution
         *     replaced and what a cancellation cancelled, since both need exactly the
         *     same information: which entry, and what to call it. Never None.entry_id;
         *     the whole reference is Optional at the call site instead, for the cases
         *     where there is nothing to reference at all.
         */
        EntryRefRead: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Name */
            name: string | null;
        };
        /**
         * EntryStatus
         * @enum {string}
         */
        EntryStatus: "scheduled" | "substituted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanCreate */
        PlanCreate: {
            /** Ends On */
            ends_on?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Visible To Friends
             * @default false
             */
            visible_to_friends: boolean;
        };
        /** PlanRead */
        PlanRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ends On */
            ends_on: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Visible To Friends */
            visible_to_friends: boolean;
        };
        /** PlanUpdate */
        PlanUpdate: {
            /** Ends On */
            ends_on?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Starts On */
            starts_on?: string | null;
            /** Visible To Friends */
            visible_to_friends?: boolean | null;
        };
        /** ResolvedEntryRead */
        ResolvedEntryRead: {
            /** Completion Id */
            completion_id: string | null;
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Name */
            name: string | null;
            /** Notes */
            notes: string | null;
            replaced: components["schemas"]["EntryRefRead"] | null;
            status: components["schemas"]["EntryStatus"];
            /** Workout Id */
            workout_id: string | null;
        };
        /** ScheduleEntryCreate */
        ScheduleEntryCreate: {
            /** Day Of Week */
            day_of_week?: number | null;
            /** Ends On */
            ends_on?: string | null;
            /** Name Override */
            name_override?: string | null;
            /** On Date */
            on_date?: string | null;
            /** Replaces Entry Id */
            replaces_entry_id?: string | null;
            /** Starts On */
            starts_on?: string | null;
            /** Workout Id */
            workout_id?: string | null;
        };
        /** ScheduleEntryRead */
        ScheduleEntryRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Day Of Week */
            day_of_week: number | null;
            /** Ends On */
            ends_on: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Override */
            name_override: string | null;
            /** On Date */
            on_date: string | null;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Replaces Entry Id */
            replaces_entry_id: string | null;
            /** Starts On */
            starts_on: string | null;
            /** Workout Id */
            workout_id: string | null;
        };
        /** ScheduleEntryUpdate */
        ScheduleEntryUpdate: {
            /** Day Of Week */
            day_of_week?: number | null;
            /** Ends On */
            ends_on?: string | null;
            /** Name Override */
            name_override?: string | null;
            /** On Date */
            on_date?: string | null;
            /** Replaces Entry Id */
            replaces_entry_id?: string | null;
            /** Starts On */
            starts_on?: string | null;
            /** Workout Id */
            workout_id?: string | null;
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Days */
            days: {
                [key: string]: components["schemas"]["DayScheduleRead"];
            };
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "minutes" | "hours" | "miles" | "kilometers" | "sets" | "reps";
        /** UnitInfo */
        UnitInfo: {
            dimension: components["schemas"]["Dimension"];
            unit: components["schemas"]["Unit"];
        };
        /** User */
        User: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkoutCreate */
        WorkoutCreate: {
            activity?: components["schemas"]["Activity"] | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutRead */
        WorkoutRead: {
            activity: components["schemas"]["Activity"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
        };
        /** WorkoutUpdate */
        WorkoutUpdate: {
            activity?: components["schemas"]["Activity"] | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activities_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitiesResponse"];
                };
            };
        };
    };
    list_completions_completions_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                activity?: components["schemas"]["Activity"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_completion_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_completion_completions__completion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                completion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_completion_completions__completion_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                completion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    list_plans_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"][];
                };
            };
        };
    };
    create_plan_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_plans__plan_id__schedule_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_plans__plan_id__schedule_entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_plans__plan_id__schedule_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_plans__plan_id__schedule_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_plans__plan_id__schedule_entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workouts_plans__plan_id__workouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_plans__plan_id__workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_plans__plan_id__workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_plans__plan_id__workouts__workout_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
