"""create schedule_entries table

Revision ID: dc11283b4452
Revises: f07cfb72fd0a
Create Date: 2026-08-05 23:01:48.515278

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc11283b4452"
down_revision: str | Sequence[str] | None = "f07cfb72fd0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=True),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("on_date", sa.Date(), nullable=True),
        sa.Column("replaces_entry_id", sa.Uuid(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("name_override", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("notes_override", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(day_of_week IS NOT NULL) <> (on_date IS NOT NULL)",
            name="ck_schedule_entries_day_xor_date",
        ),
        sa.CheckConstraint(
            "day_of_week IS NULL OR (day_of_week BETWEEN 1 AND 7)",
            name="ck_schedule_entries_day_of_week_range",
        ),
        sa.CheckConstraint(
            "ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on",
            name="ck_schedule_entries_ends_after_starts",
        ),
        sa.CheckConstraint(
            "workout_id IS NOT NULL OR name_override IS NOT NULL",
            name="ck_schedule_entries_workout_or_override",
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["replaces_entry_id"],
            ["schedule_entries.id"],
        ),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_entries_plan_id"), "schedule_entries", ["plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_entries_plan_id"), table_name="schedule_entries")
    op.drop_table("schedule_entries")
    # ### end Alembic commands ###
